name: Build Gradle project

on:
  workflow_call:
    inputs:
      upload-artifacts:
        required: false
        type: boolean
        default: false
  push:


jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"

    - name: Run build
      run: ./gradlew build

    - if: ${{ inputs.upload-artifacts }}
      name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build Files
        path: build/libs