name: Create Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-gradle-project:
    uses: ./.github/workflows/build-gradle-project.yml
    with:
      upload-artifacts: true

  create-release:
    needs: build-gradle-project
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Build Files
        uses: actions/download-artifact@v4
        with:
          name: Build Files
          path: build/libs
      - name: Create Release
        id: create_release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          title: ${{ github.ref.tags }}
          workdir: build/libs